# This file was generated by GoReleaser. DO NOT EDIT.
cask "macstrap" do
  version "0.6.1"

  on_macos do
    on_intel do
      sha256 "e02bf04c644b4e791c4939b14b4a45451669b271966183036a784c8b9a1dbb37"
      url "https://github.com/XavierAgostino/macstrap/releases/download/v#{version}/macstrap_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "35bb142764e675ca7f61c137cd1fd67226f7cee91cf933d2d07f979335c96f84"
      url "https://github.com/XavierAgostino/macstrap/releases/download/v#{version}/macstrap_darwin_arm64.tar.gz"
    end
  end

  name "macstrap"
  desc "Bootstrap a modern macOS dev environment, in one command"
  homepage "https://github.com/XavierAgostino/macstrap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "macstrap"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/macstrap"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This installs the macstrap binary only. For the full fresh-Mac bootstrap
    (Homebrew packages, dotfiles, runtimes), run:
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/XavierAgostino/macstrap/main/install.sh)"
  EOS
end
